### PR TITLE
Created MRML v3 for SENSE and added new BandwidthService

### PR DESCRIPTION
**Pull request by jmacauley**
As part of the SENSE project we spawn a new schema version.

Added new BandwidthService to track port capacities and bandwidth utilized by a service.

Closes issue https://github.com/MAX-UMD/nml-mrml/issues/10.

### CODE REVIEW

**Comment by xi-yang** [comment]
1. Typo: Several occurrences of BandwithService -> should be BandwidthService.

2. `capacity` had already been defined with domain `NetworkObject`. It was redefined with domain `BandwidthService`.

**Comment by jmacauley** [comment]
BandwithService -> Good catch.  Figures I copy the one with the incorrect spelling :-(

The existing capacity definition is:

    

    <owl:DatatypeProperty rdf:about="http://schemas.ogf.org/mrs/2013/12/topology#capacity">
        <rdfs:domain rdf:resource="http://schemas.ogf.org/nml/2013/03/base#NetworkObject"/>
        <rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#string"/>
    </owl:DatatypeProperty>

Can I remove this one?  It is defined as a string instead of a long and is bound to NetworkObject instead of the Bandwidth service.  Are you using this definition in any other objects?

**Comment by xi-yang** [comment]
We used `mrs:capacity` to represent "general" capacity, not limited to network elements. That is why it is a string (with unit embedded).

We can either reuse this or add maximumCapacity for BandwidthService.

**Comment by jmacauley** [comment]
I am okay with changing "capacity" to "maximumCapacity", however, capacity was also used on the instantiated port to indicate how much capacity that port was using as part of the service.  Should I create a "usedCapacity" to identify the capacity used by the service instance?

**Comment by xi-yang** [comment]
I am fine with adding `usedCapacity`. These attributes are all optional.

**Comment by jmacauley** [comment]
I know you like shorter names.  Looking at the ones we have now it is possible to shorten them since they are in the context of the BandwidthService:

reservableCapacity == reservable
granularity == granularity
availableCapacity == available
maximumCapacity == maximum
usedCapacity == used
unit == unit

What do you think?

**Comment by xi-yang** [comment]
These are good in the context of BandwidthService, but could be confusing within the bigger mrs space, unless we expand these attributes to generally apply to other resources and services, and make the `unit' more general as well.

**Pull request merged**
